apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-secure
  labels:
    app: fastapi-secure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-secure
  template:
    metadata:
      labels:
        app: fastapi-secure
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: fastapi
          image: registry.gitlab.com/obi1kenobi471/test_task/app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      volumes:
        - name: tmp
          emptyDir: {}