apiVersion: v1
kind: Service
metadata:
  name: fastapi-secure-service
  labels:
    app: fastapi-secure
spec:
  selector:
    app: fastapi-secure
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP